@host=https://localhost:7195
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNWVhYjE0Ni1kMWZjLTQ5NGYtOTUyNS1jNDE3NjczNjYwZmQiLCJnaXZlbl9uYW1lIjoidGVzdCIsImZhbWlseV9uYW1lIjoidHNldCIsImp0aSI6ImU2MzYyMTBiLTdlZGItNDkwOC1iODE5LTNjYzU1YTdjOWY1ZCIsImV4cCI6MTczODM0NTc1OCwiaXNzIjoiRHViZXJEaW5uZXIiLCJhdWQiOiJEdWJlckRpbm5lciJ9.jnt3tPPl_rKP-GawbMZQ7_WYPKMIYruYeZ7J-3WE86U
@hostId=00000000-0000-0000-0000-000000000000

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}